version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ENVIROMENT=${SERVER_ENVIROMENT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_AUTH_TOKEN_DURATION=${JWT_AUTH_TOKEN_DURATION}
      - BCRYPT_HASHING_SALT=${BCRYPT_HASHING_SALT}
      - ENCRYPTION_SALT=${ENCRYPTION_SALT}
      - ENCRYPTION_SECRET_KEY=${ENCRYPTION_SECRET_KEY}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nestjs-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

volumes:
  postgres_data:

networks:
  nestjs-network:
    driver: bridge